### ISSUE TITLE
Matriz de stakeholders CR

### ISSUE THREAD

**Issue by mafeermoreno** [Black-Dot-2024/docs#111]
## Task
- [x] Identificar actores
- [x] Identificar poderes e intereses de los actores
- [x] Crear documento draw.io
- [x] Plasmar a los actores

## Extras
-

**Comment by mafeermoreno** [comment]
Link: https://drive.google.com/file/d/1gp4iYAXKIAT1oL7ZXSLpSrGQavRrxKd9/view?usp=sharing
