### ISSUE TITLE
Matriz de stakeholders Zeitgeist

### ISSUE THREAD

**Issue by Ian326** [Black-Dot-2024/docs#115]
## Descripción
Elaboración de la matriz de stakeholders

## Task
- [x] Identificar actores
- [x] Identificar poderes e intereses de los actores
- [x] Crear documento draw.io
- [x] Plasmar a los actores

## Extras
¯\_(ツ)_/¯
