### ISSUE TITLE
Visión del proyecto CR

### ISSUE THREAD

**Issue by OlimpiaGarcia** [Black-Dot-2024/docs#16]
## Descripción
Definir la visión del proyecto, de acuerdo al [proceso](https://github.com/Black-Dot-2024/docs/wiki/PRO%E2%80%90BDT%E2%80%90005-Definir-visi%C3%B3n-del-proyecto).

## Tasks
- [x] Creación de la página en la wiki de GH
- [x] Objetivo
- [x] Arquitectura
- [x] Criterios de éxito
- [x] Hitos del proyecto
- [x] Número de iteraciones
- [x] Riesgos

## Extra
> [!NOTE] 
> Revisar diapositiva de visión de proyecto de DAD
