### ISSUE TITLE
Definición Ready y Done

### ISSUE THREAD

**Issue by DanielSebasCM** [Black-Dot-2024/docs#160]
## Descripción
Hacer una propuesta de definición de READY y DONE basadas en DAD y validarla con el equipo

## Task
- [x] Propuesta de READY
- [x] Propuesta de DONE 
- [x] Aprobación del equipo

## Extras
- Libro de Disciplined Agile Delivery

**Comment by CharlesVela66** [comment]
Claro, aquí está:
https://github.com/Black-Dot-2024/docs/blob/develop/docs/cr/ready-y-done.md
