### ISSUE TITLE
SCAMPI B - SCAMPI Interno PP

### ISSUE THREAD

**Issue by danfupo03** [Black-Dot-2024/docs#166]
## Descripción
El equipo asignado deberá revisar la retroalimentación que se encuentra en el excel de SCAMPI

## Task
- [x]  Revisar la retroalimentación
- [ ]  Resolver dudas sobre la retroalimentación (en caso de existir)
- [ ]  Anotar las revisiones en el *Log de revisiones*
- [ ]  Compartir las revisiones con el departamento
- [ ]  Definir responsables

## Extras
-
