### ISSUE TITLE
SCAMPI B - SCAMPI Interno REQM

### ISSUE THREAD

**Issue by danfupo03** [Black-Dot-2024/docs#167]
## Descripción
El equipo asignado deberá revisar la retroalimentación que se encuentra en el excel de SCAMPI

## Task
- [x]  Revisar la retroalimentación
- [x]  Resolver dudas sobre la retroalimentación (en caso de existir)
- [x]  Anotar las revisiones en el *Log de revisiones*
- [x]  Compartir las revisiones con el departamento
- [x]  Definir responsables

## Extras
-

**Comment by FridaBG** [comment]
SP 1.3
- [x]  Revisar la retroalimentación
- [x]  Resolver dudas sobre la retroalimentación (en caso de existir)
- [x]  Anotar las revisiones en el *Log de revisiones*
- [ ]  Compartir las revisiones con el departamento
- [ ]  Definir responsables
