### ISSUE TITLE
SCAMPI B - SCAMPI Interno PMC

### ISSUE THREAD

**Issue by danfupo03** [Black-Dot-2024/docs#168]
## Descripción
El equipo asignado deberá revisar la retroalimentación que se encuentra en el excel de SCAMPI

## Task
- [x]  Revisar la retroalimentación
- [x]  Resolver dudas sobre la retroalimentación (en caso de existir)
- [x]  Anotar las revisiones en el *Log de revisiones*
- [x]  Compartir las revisiones con el departamento
- [ ]  Definir responsables

## Extras
-

**Comment by RamonaNF** [comment]
[Log de revisiones](https://docs.google.com/document/d/1AkHer2xZvfLYBPNCZtNvDG99-N4YUiEf9Fje2_lWOKY/edit?usp=sharing)
