### ISSUE TITLE
SCAMPI B - Analizar REQM

### ISSUE THREAD

**Issue by danfupo03** [Black-Dot-2024/docs#170]
## Descripción
El equipo asignado deberá analizar el área de proceso, y también, deberá realizar un resumen entendible para el resto del Departamento. 

## Task
- [x]  Leer el área de proceso de CMMI
- [x]  Revisar el SCAMPI de ese área de proceso
- [x]  Resolver dudas sobre el área de proceso (en caso de existir)
- [x]  Redactar resumen en equipo
- [x]  Compartir su resumen con el departamento

## Extras
-

**Comment by FridaBG** [comment]
✍ [Resumen REQM](https://docs.google.com/document/d/1HI_TldzN_QPqCfYdrBHJElqWSUsHLjgraHNM2wZ7yR4/edit?usp=sharing)

**Comment by FridaBG** [comment]
SP 1.3

- [x]  Leer el área de proceso de CMMI
- [x]  Revisar el SCAMPI de ese área de proceso
- [x ]  Resolver dudas sobre el área de proceso (en caso de existir)
- [x]  Redactar resumen en equipo
- []  Compartir su resumen con el departamento
