### ISSUE TITLE
SCAMPI B - Analizar PMC

### ISSUE THREAD

**Issue by danfupo03** [Black-Dot-2024/docs#171]
## Descripción
El equipo asignado deberá analizar el área de proceso, y también, deberá realizar un resumen entendible para el resto del Departamento. 

## Task
- [x]  Leer el área de proceso de CMMI
- [x]  Revisar el SCAMPI de ese área de proceso
- [ ]  Resolver dudas sobre el área de proceso (en caso de existir)
- [x]  Redactar resumen en equipo
- [x]  Compartir su resumen con el departamento

## Extras
-

**Comment by mafeermoreno** [comment]
Link: https://docs.google.com/document/d/1qNqhFDrbMvCTAzqrzPatwEFtczJBl1pwe4PuMKnJwPA/edit#heading=h.alhltcl3rmkf
