### ISSUE TITLE
SCAMPI B- Analizar PPQA

### ISSUE THREAD

**Issue by danfupo03** [Black-Dot-2024/docs#173]
## Descripción
El equipo asignado deberá analizar el área de proceso, y también, deberá realizar un resumen entendible para el resto del Departamento. 

## Task
- [ ]  Leer el área de proceso de CMMI
- [ ]  Revisar el SCAMPI de ese área de proceso
- [ ]  Resolver dudas sobre el área de proceso (en caso de existir)
- [ ]  Redactar resumen en equipo
- [ ]  Compartir su resumen con el departamento

## Extras
-
