### ISSUE TITLE
SCAMPI B - Analizar CM

### ISSUE THREAD

**Issue by danfupo03** [Black-Dot-2024/docs#174]
## Descripción
El equipo asignado deberá analizar el área de proceso, y también, deberá realizar un resumen entendible para el resto del Departamento. 

## Task
- [x]  Leer el área de proceso de CMMI
- [x]  Revisar el SCAMPI de ese área de proceso
- [x]  Resolver dudas sobre el área de proceso (en caso de existir)
- [x]  Redactar resumen en equipo
- [x]  Compartir su resumen con el departamento

## Extras
-
