### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by lCDSLl-Richard** [Black-Dot-2024/docs#177]
## Descripción
Crear un Dashboard dónde se pueda consultar la información del proyecto

## Task
- [ ] El Dashboard muestra la medición de calidad
- [ ] El Dahsboard muestra la medición de costo
- [ ] El Dashboard muestra el progreso del proyecto
- [ ] El Dashboard muestra el estado del equipo

**Comment by OlimpiaGarcia** [comment]
Necesito las estimaciones de esto para el PVG, pls.
