### ISSUE TITLE
Log Patrones y Antipatrones

### ISSUE THREAD

**Issue by lCDSLl-Richard** [Black-Dot-2024/docs#178]
## Descripción
Crear un log dónde llevemos registro de los [patrones y antipatrones](https://docs.google.com/presentation/d/17J3JHpvTvDHHYR-ZVY3EzhteJNJu-fhG6A39OTNyh3Q) vistos en clase de Lalo

## Task
- [x] Existe un log con este fin
- [x] Se ha llenado el log con los patrones y antipatrones
- [x] Hay almenos un registro de una iteración

**Comment by RamonaNF** [comment]
[Log patrones y antipatrones Zeitgeist](https://docs.google.com/spreadsheets/d/1gSc30wbf5dufiwZhhw-YRbiHULDQOOg__4OtwjRhQI0/edit?usp=sharing)

¿A qué se refiere con "hay al menos un registro de cada proyecto"?

**Comment by lCDSLl-Richard** [comment]
En mi cabeza esto era para ambos equipos, pero supongo que mejor solo para nosotros, deja cambio las especificaciones
