### ISSUE TITLE
Refinamiento del PVG

### ISSUE THREAD

**Issue by lCDSLl-Richard** [Black-Dot-2024/docs#179]
## Descripción
Refinamiento de los ítems de trabajo en el PVG

## Task
- [ ] Agregar items que se hicieron pero no se tenían planeados
- [ ] Agregar tiempo en los ítems completados
- [ ] Arreglar las gráficas

## Extras
-
