### ISSUE TITLE
ZG. Log de Riesgos

### ISSUE THREAD

**Issue by sebFlores02** [Black-Dot-2024/docs#185]
## Descripción
Recopilar información y crear reporte log de Riesgos ZG

## Task
- [x] Recopilar información basada en las daily's realizadas
- [x]  Crear plantilla del log
- [x] Agregar información a la plantilla

## Extras
-
