### ISSUE TITLE
Guia de despliegue

### ISSUE THREAD

**Issue by DHurtado714-itesm** [Black-Dot-2024/docs#190]
## Task

- [ ]  Instalar paquetes (git, node, pnpm, caddy, pm2)
- [ ]  Clonar y correr el proyecto con pm2
- [ ]  Configurar el reverse proxy
- [ ]  Desplegar en Vercel

## Extras
-

**Comment by RodrigoTeran** [comment]
Pueden irse anotando en las tasks en lo que quieran ayudar porfa :)

No importa si hay varios por task
