### ISSUE TITLE
Guia de Firebase

### ISSUE THREAD

**Issue by DHurtado714-itesm** [Black-Dot-2024/docs#191]
## Task
- [ ]  Configurar el proyecto en general
- [ ]  Como configurar e integrar Autenticacion
- [ ]  Como configurar e integrar Notificaciones

## Extras
-
