### ISSUE TITLE
Guia de desarrollo

### ISSUE THREAD

**Issue by DHurtado714-itesm** [Black-Dot-2024/docs#192]
## Descripción

En dado caso que alguien se quiera integrar al equipo, que explique y haga el onboarding.

## Task
- [ ] Explicar que herramientas descargar
- [ ] Que paquetes necesita instalar
- [ ] Donde encontrar las claves para los diferentes entornos

## Extras
- Esta guia puede ser solo 1 con todo en conjunto

**Comment by FridaBG** [comment]
- Queda pendiente la parte de migración de prisma, @DHurtado714-itesm investigará eso.

**Comment by FridaBG** [comment]
📝 [Guía de Desarrollo](https://docs.google.com/document/d/1HwECr20R2kS1TkzVTZPYKrXVyDxuxsiv2lz1-cBcdW0/edit?usp=drive_link)
