### ISSUE TITLE
Pasar guias a la Wiki

### ISSUE THREAD

**Issue by Ian326** [Black-Dot-2024/docs#194]
## Descripción
Formalizar la prueba de arquitectura para el proyecto LinkBridge

## Task
- [ ] Guia de Despliegue
- [ ] Guia de Desarrollo
- [ ] Guia de integración de servicios

## Extras
- Migraciones con Prisma
- ¯\_(ツ)_/¯
