### ISSUE TITLE
Definir necesidad CR

### ISSUE THREAD

**Issue by OlimpiaGarcia** [Black-Dot-2024/docs#2]
## Tasks
- [x] Definir necesidad 
- [x] Validar necesidad con profes
- [x] Validar necesidad con el grupo
- [x] Validar necesidad con Socio
- [x] Plasmada en Github

## Extra
