### ISSUE TITLE
PPQA. Iniciando la Definición

### ISSUE THREAD

**Issue by yna2131** [Black-Dot-2024/docs#202]
## Descripción
Empezar a definir nuestro WoW para el área de PPQA (Process and Product Quality Assurance)

## Task
- [ ] Revisar los SPs de PPQA
- [ ] Generar ideas para procesos
- [ ] Generar ideas para auditorías

## Extras
> Ya definimos que las auditorías se realizarán a través de Checklists
