### ISSUE TITLE
PP. Mejora Continua

### ISSUE THREAD

**Issue by yna2131** [Black-Dot-2024/docs#203]
## Descripción
Revisar y mejorar los procesos y ítems del trabajo que está relacionado con el área de PP (Project Planning)

## Task
- [ ] Revisar y actualizar **PRO-BDT-014 Planeación de un proyecto**
  - [ ] Incluir nota introductoria: **¿Por qué usamos el Ciclo de Vida (DAD) que estamos utilizando?**
  - [ ] Adaptar el proceso más a nuestro departamento a través de guías, estándares, procesos y definiciones
- [ ] PVG
  - [ ] Indicador, guía, o alguna explicación de **¿Qué SP equivale a qué Costo?¿Por qué?**
- [ ] Revisar y actualizar Plan de Recurso
  - [ ] Sugerencia: Guía para la identificación de recursos del proyecto
  - [ ] Sugerencia: Log de Aprendizaje que incluye
    - Herramientas
      - CR
      - ZG
      - Github
      - Excel
    - Competencias (11)
    - Definir niveles de conocimiento
    - Nivel inicial
    - Nivel esperado
- [ ] Revisar Plan de Comunicación

## Extras
> Revisen el [SCAMPI Interno C](https://docs.google.com/document/d/1AkHer2xZvfLYBPNCZtNvDG99-N4YUiEf9Fje2_lWOKY/edit?usp=sharing) para ver la retroalimentación que tuvimos en cada práctica específica :)

**Comment by alejandraa-cruiz** [comment]
Estoy actualizando también las actas de ambos proyectos para que sean concordantes. Uri y Frida están en plan de comunicación :)

**Comment by dvegaa20** [comment]
Estoy haciendo el log de aprendizaje, la sugerencia para el plan de recursos

**Comment by DamarizLicea** [comment]
Voy a revisar el PRO 14 y actualizarle lo de DAD junto con @VON0222

**Comment by DamarizLicea** [comment]
@VON0222 y yo ya terminamos las actividades del PRO14 que dijimos, cualquier cosa nos avisan @ricardo020202 @DavidLangarica

**Comment by DamarizLicea** [comment]
Ya hicimos lo de DAD también

**Comment by DavidLangarica** [comment]
Ya está la actualización de las primeras 3 actividades

**Comment by alejandraa-cruiz** [comment]
![Image](https://github.com/Black-Dot-2024/docs/assets/105231986/ad1ee7e5-cb8c-4ab9-a1c6-d228c57fd703)

No olviden llenar el PVG Departamental con el tiempo que les esta tomando :)))

**Comment by alejandraa-cruiz** [comment]
Ya esta Visión del Proyecto Talent 360 ¿qué falta para el PRO-BDT-14?

**Comment by DamarizLicea** [comment]
llaca y yo nos asignamos s plan de recursos, si alguien nos quiere ayudar avisennos
