### ISSUE TITLE
MA. Iniciando la Definición

### ISSUE THREAD

**Issue by yna2131** [Black-Dot-2024/docs#204]
## Descripción
Empezar a definir los WoWs relacionados al área de MA (Measurements and Analysis)

## Task
- [ ] Completar el Proceso para Gestión de Métricas
- [ ] Completar la Guía para Creación de Métrica
- [ ] Completar la Guía para Análisis de Métrica
- [ ] Revisar y mejorar [Dashboard de Métricas](https://docs.google.com/spreadsheets/d/1npTnrPT9SUk0jRg8OLzNRqTuQ6aYK3kIucTj3ncBDqw/edit?usp=sharing)
