### ISSUE TITLE
Definir estrategia de ingeniería

### ISSUE THREAD

**Issue by danfupo03** [Black-Dot-2024/docs#22]
## Descripción
Creación de la estrategia de desarrollo de los proyectos del departamento

## Task
- [x] Investigar de ser necesario
- [x] Crear página de la wiki
- [x] Definir ciclo de vida ágil
- [x] Definir hitos en el ciclo de vida

## Extras
-  Lo vimos con Lalo y creo que con Claud

> [!NOTE]
> Se refiere al ciclo de vida del software SDLC
> Verificar si hay procesos del tema
>Verificar si la visión del proyecto cumple con esto
