### ISSUE TITLE
CR-Plan de calidad

### ISSUE THREAD

**Issue by danfupo03** [Black-Dot-2024/docs#23]
## Tasks
- [x] Crear página de la wiki
- [x] Checar si es un proceso
- [x] Si es un proceso crear el proceso
- [x] Cumplir con los requisitos aquí detallados

## Extra
Elemento | Descripción
-- | --
Alcance | Se definen los Escenarios de Prueba que serán validados
Fuera del Alcance | Mayor claridad sobre lo que no se va a cubrir
Supuestos | Todas las condiciones que deben ser ciertas para que se pueda proceder con éxito
Calendario | Actividades: Preparación, Documentación de Casos de prueba, Datos de Prueba, Instalar Ambiente, Ejecución de Pruebas, Ciclos de Pruebas, Fechas de Inicio y Fin
Roles y Responsabilidades | Se lista los nombre del equipo QA y sus actividades asignadas

Entregables | ¿Qué documentos (artefactos de prueba) se van a producir y en qué momento?
-- | --
Ambiente de Pruebas | ¿Cuáles son los requerimientos del ambiente de pruebas? ¿Quién será el responsables del ambiente? ¿Qué procederá en caso de tener problemas?
Herramientas | Herramienta de Seguimiento de Defectos (Bug Tracking). Ejemplos: JIRA, Bugzilla, Mantis, etc.
Gestión de Defectos | ¿A quién se reportan los errores? ¿Cómo se espera que se reporten (texto, screenshots, etc)? ¿Cuál será la clasificación y prioridad de errores (criterios)?
Riesgos | Listar riesgos detectados, clasificar riesgos, plan de mitigación de riesgos
Criterio de Salida | Definir en qué momento se termina el procesos de pruebas

> [!NOTE] 
> Claud dio templates que pueden usar

**Comment by dvegaa20** [comment]
ya quedó lista, se corrigieron errores y se mandó a la wiki
