### ISSUE TITLE
RF04: Consultar detalle de tarea

### ISSUE THREAD

**Issue by RamonaNF** [Black-Dot-2024/docs#234]
## Descripción
Como colaborador de un departamento, quiero consultar la información detallada de una tarea de un proyecto para conocer la información más concreta.

## Tasks
- [ ] El sistema muestra la información de una tarea.
- [ ] La información que muestra el sistema es: 
    - [ ] Descripción
    - [ ] Fecha de inicio
    - [ ] Fecha de finalización
    - [ ] Responsable
    - [ ] Horas trabajadas
    - [ ] Proyecto al que pertenece
    - [ ] Estatus de la tarea

## Extras
![Image](https://github.com/Black-Dot-2024/docs/assets/91426086/2bcba84e-713e-4197-8095-77b8a02ebdd2)
