### ISSUE TITLE
Plan de riesgos

### ISSUE THREAD

**Issue by danfupo03** [Black-Dot-2024/docs#24]
## Descripción
Crear un plan de riesgos para identificarlos, como responder y mitigarlos

## Tasks 

- [x] Hacer proceso
- [x] Plan de riesgos CR
- [x] Plan de riesgo ZG
- [x] Plan de riesgo departamental
- [x] Plan de mitigación ZG
- [x] Plan de contingencia ZG

## Extras
**Establecer la estrategia para gestionar los riesgos**
SG1. La preparación de la gestión de los riesgos es llevada a cabo

> SP1.1 Determinar fuentes y categorías de riesgos.

> SP1.2 Definir parámetros usados para analizar y categorizar riesgos y para controlar el esfuerzo de la gestión de riesgos.

> SP1.3 Establecer y mantener la estrategia que se usará para la gestión de riesgos.

**Identificar y analizar los posibles riesgos**
SG2 Los riesgos son identificados y analizados para determinar su importancia relativa.

> SP2.1 Identificar y documentar los riesgos

> SP2.2 Evaluar y categorizar cada riesgo identificado usando categorías y parámetros  de riesgo definidos, y determinar su prioridad relativa.

**Controlar los riesgos**
SG3 Los riesgos son tratados y mitigados según sea apropiado para reducir los impactos adversos para alcanzar los objetivos.

> SP3.1 Desarrollar un plan de mitigación de riesgos de acuerdo con la estrategia de gestión de riesgos.

> SP3.2 Monitorizar el estado de cada riesgo periódicamente e implementar el plan de mitigación de riesgos según sea apropiado.

> [!NOTE]
> Checar con los Cepillenes el proceso para llevarlo a cabo 
> Si no hay proceso, crearlo

**Comment by alejandraa-cruiz** [comment]
**No hay proceso, hay que crearlo**. Lo único que existe es la identificación de riesgos en el Project Charter en una matriz de riesgos que solo atiende una parte de las SP1.1 Avísenme si quieren crear ustedes el proceso para aprender :)

**Comment by DHurtado714-itesm** [comment]
Ya se completo la primer version del plan de riesgos para el proyecto de ZG.
