### ISSUE TITLE
RF62: Home page

### ISSUE THREAD

**Issue by RamonaNF** [Black-Dot-2024/docs#287]
## Descripción
Como usuario, quiero poder visualizar en la pantalla de inicio los proyectos y los clientes en donde estoy involucrado, (proyectos donde tengo tareas asignadas y clientes donde tengo proyectos con tareas asignadas)

## Task
- [ ] El sistema permite acceder a los usuarios a la página de  “Home” desde la sidebar.
- [ ] El sistema muestra únicamente los proyectos donde tiene tareas asignadas al usuario y clientes que tienen proyectos con tareas asignadas a ese usuario .
- [ ] En la sección de proyectos, se muestra la pantalla con la lista de todos los proyectos ordenados por status (el status de “Done” debe de ser el último que aparece).

## Extras
-
