### ISSUE TITLE
Definir necesidad ZG

### ISSUE THREAD

**Issue by OlimpiaGarcia** [Black-Dot-2024/docs#3]
## Tasks
- [x] Definir necesidad 
- [x] Validar necesidad con profes
- [x] Validar necesidad con el grupo
- [x] Validar necesidad con Socio
- [x] Plasmada en Github

## Extra

**Comment by yna2131** [comment]
### **Necesidad validada con los profesores y el departamento**
> Mejorar la trazabilidad y continuidad de las actividades de los proyectos de la empresa y facilitar la comunicacón de éstos entre los departamentos legal y contable.
