### ISSUE TITLE
RF 43 | Generar reportes clima

### ISSUE THREAD

**Issue by mafeermoreno** [Black-Dot-2024/docs#307]
## Descripción
Como Cliente de CR quiero generar los reportes de una evaluación de tipo clima, para acceder fácilmente a los resultados.

## Task
- [x] El sistema identifica y analiza las respuestas respondidas y obtiene puntajes por categorías y porcentaje.
- [x] El sistema grafica por departamento el porcentaje obtenido por categoría.
- [x] El sistema presenta los resultados de cada categoría
- [x] El sistema presenta resumen por categorías con un gráfico radial.
- [x] El sistema promedia el puntaje general obtenido por la compañía.
- [x] El sistema pinta los gráficos de categorías, departamentos y los promedios según el semáforo personalizable.
- [x] El sistema muestra gráficos según datos demográficos.

## Estimación
- M - 3
