### ISSUE TITLE
Proceso de toma de decisiones

### ISSUE THREAD

**Issue by DavidLangarica** [Black-Dot-2024/docs#31]
## Tasks
- [x] Creación de proceso
- [x] Validación del proceso
- [x] Verificar que el proceso este disponible en la wiki

## Extra
