### ISSUE TITLE
Plan Departamental

### ISSUE THREAD

**Issue by danfupo03** [Black-Dot-2024/docs#33]
## Descripción 
Entregable de las primeros 5 semanas

## Tasks
- [x]  https://github.com/Black-Dot-2024/docs/issues/17
- [x] https://github.com/Black-Dot-2024/docs/issues/16
- [x] https://github.com/Black-Dot-2024/docs/issues/48
- [x] https://github.com/Black-Dot-2024/docs/issues/20
- [x] https://github.com/Black-Dot-2024/docs/issues/19
- [x] https://github.com/Black-Dot-2024/docs/issues/21
- [x] https://github.com/Black-Dot-2024/docs/issues/22
- [x] https://github.com/Black-Dot-2024/docs/issues/23
- [x] https://github.com/Black-Dot-2024/docs/issues/51
- [x] https://github.com/Black-Dot-2024/docs/issues/28
- [x] https://github.com/Black-Dot-2024/docs/issues/25
- [x] https://github.com/Black-Dot-2024/docs/issues/24
- [x] https://github.com/Black-Dot-2024/docs/issues/26
- [x] https://github.com/Black-Dot-2024/docs/issues/74
- [x] https://github.com/Black-Dot-2024/docs/issues/75
- [x] https://github.com/Black-Dot-2024/docs/issues/27
- [x] https://github.com/Black-Dot-2024/docs/issues/49

## Extra
