### ISSUE TITLE
Presentación de Departamento y Proyectos

### ISSUE THREAD

**Issue by OlimpiaGarcia** [Black-Dot-2024/docs#34]
## Tasks
- [x] [Necesidad ZG ](https://github.com/Black-Dot-2024/docs/issues/3)
- [x] [Necesidad CR](https://github.com/Black-Dot-2024/docs/issues/2)
- [x] [Objetivos Departamentales](https://github.com/Black-Dot-2024/docs/issues/1)
- [x] [Misión, visión, valores](https://github.com/Black-Dot-2024/docs/wiki/Misi%C3%B3n,-Visi%C3%B3n,-Valores-y-Objetivos:)
- [x] [Estructura y roles del equipo](https://github.com/Black-Dot-2024/docs/wiki/Equipo:)
## Extra
