### ISSUE TITLE
Guia de  Creación de Presentación Cliente

### ISSUE THREAD

**Issue by alejandraa-cruiz** [Black-Dot-2024/docs#39]
## Descripción
El propósito es que las presentaciones de avance tenga calidad y sean de valor para el cliente o el equipo.
## Tasks
- [x] Público, propósito, agenda, día y lugar
- [x] Canvas 
- [x] Uso de los colores del cliente si tiene
- [x] Uso del logo del departamento
- [x] Usar gráficas y poco texto 
- [x] Validar con el equipo
- [x] Practicar la presentación
## Extras

**Comment by alejandraa-cruiz** [comment]
Se hará una guía

**Comment by VON0222** [comment]
Queda pendiente la elaboración de un diagrama de considerarse necesario.

**Comment by alejandraa-cruiz** [comment]
La guía ya está en la página
