### ISSUE TITLE
Planear presentación final

### ISSUE THREAD

**Issue by danfupo03** [Black-Dot-2024/docs#43]
## Descripción
Planeación de nuestro plan departamental

## Tasks

- [x] Ponerse de acuerdo con el otro grupo, si ya tienen un salón
- [x] Buscar un salón en el que quepamos los dos departamentos (en caso de que no haya salón)
- [x] Hacer invitación a socios, profesores, directivos y nosotros
- [x] Se crea evento en calendario y se añade a los interesados

## Extras
- Reservar salón de 2 a 6pm (si se puede, sino de 3 a 6)
- Elenita puede ayudarlos en eso elhernan@tec.mx

**Comment by RodrigoTeran** [comment]
Esto ya quedó... ¿no @danfupo03 ?
