### ISSUE TITLE
Plan de proyecto CR

### ISSUE THREAD

**Issue by CharlesVela66** [Black-Dot-2024/docs#47]
## Descripción
Project planning para CR Organizacional

## Task:
- [x] Objetivos de los stakeholders
- [x] Habilidades del equipo
- [x] Ciclo de vida
- [x] Plan de iteraciones del proyecto
- [x] Estimación del proyecto
- [x] Entregables del proyecto
- [x] Plan de riesgos 

## Extras
- https://docs.google.com/document/d/1EkusQ-5p9i81Shs9Cs712EN2MYP7Ww5e0L0arISF2OM/edit
