### ISSUE TITLE
Cambio de política a estándar - POL-BDT-001 Identificadores de documentación

### ISSUE THREAD

**Issue by dembA7** [Black-Dot-2024/docs#52]
## Descripción
Cambiar de política a estándar la POL-BDT-001 Identificadores de documentación

## Task
- [x] Cambiar de política a estándar en wiki
- [x] Cambiar de política a estándar en drive
- [x] Cambiar de política a estándar en docusaurus

## Extras
- Ninguno
