### ISSUE TITLE
Venue para presentación final

### ISSUE THREAD

**Issue by OlimpiaGarcia** [Black-Dot-2024/docs#53]
## Descripción
Necesitamos un salón para la presentación final VIERNES 15

## Task
- [x] preguntar al otro salón si ya tienen una venue planeada
- [x] SI  el otro grupo quiere hacerlo con nosotros, buscar un lugar que albergue al menos a 70 personas
- [x] SI NO, un lugar de para 50 personas
- [x] reservar lugar de 2 a 6

## Extras
-  Le pueden preguntar a Elenita si sabe de algún salon elhernan@tec.mx
- Debe haber equipo técnico (micrófonos, proyector, etc) si se puede con AC
