### ISSUE TITLE
Proceso para resolución de conflictos

### ISSUE THREAD

**Issue by DavidLangarica** [Black-Dot-2024/docs#56]
## Tasks
- [x] Creación de proceso
- [x] Creación de guía
- [x] Validación del proceso
- [x] Verificar que el proceso este disponible en la wiki

## Extra
