### ISSUE TITLE
Tutorial Setup Odoo

### ISSUE THREAD

**Issue by DanielSebasCM** [Black-Dot-2024/docs#58]
## Descripción
Crear un video con el paso a paso para poder comenzar a desarrollar Odoo

## Task
- [x] Video siguiendo los pasos de instalación Windows
- [x] Video siguiendo los pasos de instalación MacOS
- [x] Video configurando la versión correcta de python Windows

## Extras
- Resolver dudas que queden o problemas de instalación

**Comment by DanielSebasCM** [comment]
https://drive.google.com/drive/folders/1VajNajI5zo2T-aLtE6jfmhsssBd4aoQt
