### ISSUE TITLE
Formatos: Estándares

### ISSUE THREAD

**Issue by OlimpiaGarcia** [Black-Dot-2024/docs#6]
## Descripción 
Creación de un estándar para: 

## Tasks
- [x] Nombres
- [x] Documentos en drive, 
- [x] Documentos en wiki del GitHub,
- [x] CMMI
- [x] Políticas
- [x] Manuales
- [x] US
- [x] UML
- [x] Template para Issues

**Comment by alejandraa-cruiz** [comment]
el estándar para versiones que estamos trabajando sólo funciona para desarrollo no para la parte de la wiki :(

**Comment by JP-coder2000** [comment]
Me parece que mi parte de template para Issues está lista a menos de que sea issues como tal y no el template donde van los issues @OlimpiaGarcia

**Comment by sgarnica1** [comment]
Solo falta el formato de User Story

**Comment by DHurtado714-itesm** [comment]
Yo me puedo encargar de poner el formato de las US en la wiki
