### ISSUE TITLE
Estandar de documentos derivados

### ISSUE THREAD

**Issue by OlimpiaGarcia** [Black-Dot-2024/docs#64]
## Descripción
Establecer el estandar para documentación que deriva de un proceso / guia / manual

## Task
- [x] Creación del estandar
- [x] Validado por el grupo
- [ ] se plasma en GH

## Extras
-
