### ISSUE TITLE
Documentación Faltante de la Wiki

### ISSUE THREAD

**Issue by OlimpiaGarcia** [Black-Dot-2024/docs#66]
## Descripción
Copiar los documentos para tenerlos todo en la wiki

## Task
***De Drive a Docusaurus***
- [x]  Objetivos de roles
- [x]  Plantillas documento
- [x]  Documentos de CR
- [x]  WBS requerimentos

***Wiki vieja a Docosaurus***
- [x]  Guías
- [x]  [Plantilla PL-BDT-005](https://black-dot-2024.github.io/black-dot-wiki/plantillas/pl-bdt-005) Pasar y hacer que coincida con la plantilla
