### ISSUE TITLE
Proceso de Plan de Proyecto

### ISSUE THREAD

**Issue by danfupo03** [Black-Dot-2024/docs#68]
## Descripción
Proceso que se realizará después de que ambos planes de proyecto estén realizados

## Task
- [ ] Creación de proceso
- [ ]  Creación de guía
- [ ]  Validación del proceso
- [ ]  Verificar que el proceso este disponible en la wiki

## Extras
-

**Comment by DanielSebasCM** [comment]
Ya había un issue de esto creo, https://github.com/orgs/Black-Dot-2024/projects/4/views/1?filterQuery=plan&pane=issue&itemId=54836710
