### ISSUE TITLE
Características de los Usuarios ERS

### ISSUE THREAD

**Issue by CharlesVela66** [Black-Dot-2024/docs#84]
## Descripción
Identificar usuarios en el ERS de acuerdo al formato

## Task
- [x] Identificar los tipos de usuario
- [x] Identificar su nivel educativo
- [x] Identificar su experiencia
- [x] Identificar sus actividades en el sistema  

## Extras
-
