### ISSUE TITLE
MER CR

### ISSUE THREAD

**Issue by UriGOPAR** [Black-Dot-2024/docs#85]
## Descripción
Creación del MER

## Task
- [x] Identificación de tablas
- [x] Identificación de relación
- [x] Identificación de multiplicidad   

## Extras
-

**Comment by UriGOPAR** [comment]
https://drive.google.com/file/d/1CcSSGDQPEZvocvQgz4P8qBtsIyNabA-a/view?usp=sharing

**Comment by CharlesVela66** [comment]
@ricardo020202 si puedes poner el link del MER y del diccionario de datos
