### ISSUE TITLE
Código de ética

### ISSUE THREAD

**Issue by OlimpiaGarcia** [Black-Dot-2024/docs#9]
## Descripción 
Conformación del cómite de ética
## Tasks
- [x] Investigación del código de ética
- [x] Comprender la función del comité
- [x] Comprender como se comunica el comité
- [x] Hacer código de ética
- [x] ¿Cuándo y cómo funcionaría?
- [ ] Plasmar en GH

Entregables

- [x] filosofia corporativa
- [x] codifo de etica del departamento
- [x] protocolo de actuacion del comite de integridad

Deseables:

- [x] acta de conformacion 
- [x] auerdo de confidencialidad 

## Extra

**Comment by alejandraa-cruiz** [comment]
Hola creo que esto es del Comité de Ética, no sé si estoy aquí por el proceso de como proceder de una denuncia por si tienen alguna pregunta de como hacerlo. Me voy a salir del Issue. Igual aquí esta Ramona que tiene mucha experiencia en lo de los procesos 😄 Si necesitan algo me reasignan o me mandan mensajito en Discord.
