### ISSUE TITLE
Proceso para monitorear plan de riesgo

### ISSUE THREAD

**Issue by yna2131** [Black-Dot-2024/docs#92]
## Descripción
El proceso para monitorear el plan de riesgos departamental, de Zeitgeist y de CR.

## Task
- [x] Crear el proceso
- [x] Probar el proceso
- [x] Presentar el proceso a todo el departamento

## Extras
- Este proceso es parte de los siguientes áreas de procesos: **PP, PMC, RSKM**
- Ya está hecho el proceso, nada más necesitamos probar y validarlo con el departamento
